export { default as ResidentDashboard } from './ResidentDashboard';
export { default as MyBills } from './MyBills';
export { default as Complaints } from './Complaints';
export { default as Announcements } from './Announcements';
export { default as Documents } from './Documents';
export { default as Emergency } from './Emergency';
export { default as Staff } from './Staff';
export { default as ResidentSettings } from './ResidentSettings';
export { default as VisitorPreApproval } from './VisitorPreApproval';
